<?php
/*
 * @package     Intelipost_Quote
 * @copyright   Copyright (c) 2016 Gamuza Technologies (http://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>

<script>

var INTELIPOST_QUOTE_CALENDAR_URL = "<?php echo $this->getAjaxCalendarUrl(); ?>";
var INTELIPOST_QUOTE_SCHEDULE_URL = "<?php echo $this->getAjaxScheduleUrl(); ?>";
var INTELIPOST_QUOTE_SCHEDULE_STATUS_URL = "<?php echo $this->getAjaxScheduleStatusUrl(); ?>";

</script>

