<?php
/*
 * @package     Intelipost_Quote
 * @copyright   Copyright (c) 2016 Gamuza Technologies (http://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>

<div class="footer content">
<p>
<button type="button" id="intelipost-debug-button" class="action primary" title="Intelipost Debug">
<span><?php echo __('Intelipost Debug'); ?></span>
</button>
</p><p>
<div id="intelipost-debug-result">&nbsp;<?php echo __('click the button above'); ?></div>
</p>
</div>

<script>

require([
    'jquery',
    'jquery/validate'
], function(jQuery){

jQuery("#intelipost-debug-button").click(function(){

    jQuery.ajax({
        url: '<?php echo $this->getAjaxDebugUrl() ?>',
        async: false,
        showLoader: true, // enable loader

        success: function(data) {
            jQuery('#intelipost-debug-result').html (data);
        },

        error: function() {
            jQuery('#intelipost-debug-result').text ("<?php echo __('Failure'); ?>");
        }
    });

});

});

</script>

